// import { InMemoryDbService } from 'angular-in-memory-web-api';
// import { Injectable } from '@angular/core';
// import { RawInstrument, RawInstrumentType } from './.models/instrument'; // tuotteen tyyppi
// import { RawItem } from './.models/item';
// @Injectable({
//   providedIn: 'root',
// })
// export class InMemoryDataService implements InMemoryDbService {
//   createDb() {
//     // productCategorys-taulukko on valetietokanta, jossa ovat tuotekategoriat
//     const productCategories: RawInstrumentType[] = [
//       { id_type: 1, type_name: 'Guitar' },
//       { id_type: 2, type_name: 'Piano' },
//       { id_type: 3, type_name: 'Violin' },
//       { id_type: 4, type_name: 'Harp' },
//       { id_type: 5, type_name: 'Drums' },
//       { id_type: 6, type_name: 'Accordion' },
//     ];

//     const instruments: RawInstrument[] = [
//       {
//         id_Instrument: 1,
//         name: 'Acoustic Guitar',
//         model: 'AG-001',
//         Description: 'Standard acoustic guitar',
//         Instrument_type_id: 1,
//       },
//       {
//         id_Instrument: 2,
//         name: 'Electric Guitar',
//         model: 'EG-001',
//         Description: 'Electric guitar',
//         Instrument_type_id: 1,
//       },
//       {
//         id_Instrument: 3,
//         name: 'Grand Piano',
//         model: 'GP-001',
//         Description: 'Grand piano',
//         Instrument_type_id: 2,
//       },
//       {
//         id_Instrument: 4,
//         name: 'Violin',
//         model: 'VN-001',
//         Description: 'Classical violin',
//         Instrument_type_id: 3,
//       },
//       {
//         id_Instrument: 5,
//         name: 'Concert Harp',
//         model: 'HP-001',
//         Description: 'Concert harp',
//         Instrument_type_id: 4,
//       },
//       {
//         id_Instrument: 6,
//         name: 'Drum Kit',
//         model: 'DK-001',
//         Description: 'Full drum kit',
//         Instrument_type_id: 5,
//       },
//       {
//         id_Instrument: 7,
//         name: 'Accordion',
//         model: 'AC-001',
//         Description: 'Classical accordion',
//         Instrument_type_id: 6,
//       },
//     ];

//     const items: RawItem[] = [
//       {
//         id_Item: 1,
//         barcode: 'gui-001',
//         rent_day: 15.0,
//         rent_week: 85.0,
//         rent_month: 300.0,
//         is_available: 1,
//         condition: 'excellent',
//         Instrument_id_Instrument: 1,
//       },
//       {
//         id_Item: 2,
//         barcode: 'gui-002',
//         rent_day: 15.0,
//         rent_week: 75.0,
//         rent_month: 300.0,
//         is_available: 1,
//         condition: 'good',
//         Instrument_id_Instrument: 1,
//       },
//       {
//         id_Item: 3,
//         barcode: 'gui-003',
//         rent_day: 15.0,
//         rent_week: 85.0,
//         rent_month: 300.0,
//         is_available: 1,
//         condition: 'good',
//         Instrument_id_Instrument: 1,
//       },
//       {
//         id_Item: 4,
//         barcode: 'gui-004',
//         rent_day: 18.0,
//         rent_week: 100.0,
//         rent_month: 350.0,
//         is_available: 1,
//         condition: 'excellent',
//         Instrument_id_Instrument: 2,
//       },
//       {
//         id_Item: 5,
//         barcode: 'gui-005',
//         rent_day: 18.0,
//         rent_week: 100.0,
//         rent_month: 350.0,
//         is_available: 1,
//         condition: 'good',
//         Instrument_id_Instrument: 2,
//       },
//       {
//         id_Item: 6,
//         barcode: 'gui-006',
//         rent_day: 18.0,
//         rent_week: 100.0,
//         rent_month: 350.0,
//         is_available: 1,
//         condition: 'good',
//         Instrument_id_Instrument: 2,
//       },
//       {
//         id_Item: 7,
//         barcode: 'pia-001',
//         rent_day: 50.0,
//         rent_week: 280.0,
//         rent_month: 1000.0,
//         is_available: 1,
//         condition: 'excellent',
//         Instrument_id_Instrument: 3,
//       },
//       {
//         id_Item: 8,
//         barcode: 'pia-002',
//         rent_day: 50.0,
//         rent_week: 280.0,
//         rent_month: 1000.0,
//         is_available: 1,
//         condition: 'good',
//         Instrument_id_Instrument: 3,
//       },
//       {
//         id_Item: 9,
//         barcode: 'pia-003',
//         rent_day: 50.0,
//         rent_week: 280.0,
//         rent_month: 1000.0,
//         is_available: 1,
//         condition: 'good',
//         Instrument_id_Instrument: 3,
//       },
//       {
//         id_Item: 10,
//         barcode: 'vio-001',
//         rent_day: 12.0,
//         rent_week: 70.0,
//         rent_month: 250.0,
//         is_available: 1,
//         condition: 'excellent',
//         Instrument_id_Instrument: 4,
//       },
//       {
//         id_Item: 11,
//         barcode: 'vio-002',
//         rent_day: 12.0,
//         rent_week: 70.0,
//         rent_month: 250.0,
//         is_available: 1,
//         condition: 'excellent',
//         Instrument_id_Instrument: 4,
//       },
//       {
//         id_Item: 12,
//         barcode: 'vio-003',
//         rent_day: 12.0,
//         rent_week: 70.0,
//         rent_month: 250.0,
//         is_available: 1,
//         condition: 'good',
//         Instrument_id_Instrument: 4,
//       },
//       {
//         id_Item: 13,
//         barcode: 'vio-004',
//         rent_day: 12.0,
//         rent_week: 70.0,
//         rent_month: 250.0,
//         is_available: 1,
//         condition: 'good',
//         Instrument_id_Instrument: 4,
//       },
//       {
//         id_Item: 14,
//         barcode: 'vio-005',
//         rent_day: 12.0,
//         rent_week: 70.0,
//         rent_month: 250.0,
//         is_available: 1,
//         condition: 'good',
//         Instrument_id_Instrument: 4,
//       },
//       {
//         id_Item: 15,
//         barcode: 'vio-006',
//         rent_day: 12.0,
//         rent_week: 70.0,
//         rent_month: 250.0,
//         is_available: 1,
//         condition: 'good',
//         Instrument_id_Instrument: 4,
//       },
//       {
//         id_Item: 16,
//         barcode: 'vio-007',
//         rent_day: 12.0,
//         rent_week: 70.0,
//         rent_month: 250.0,
//         is_available: 1,
//         condition: 'damaged',
//         Instrument_id_Instrument: 4,
//       },
//       {
//         id_Item: 17,
//         barcode: 'vio-008',
//         rent_day: 12.0,
//         rent_week: 70.0,
//         rent_month: 250.0,
//         is_available: 1,
//         condition: 'damaged',
//         Instrument_id_Instrument: 4,
//       },
//       {
//         id_Item: 18,
//         barcode: 'hap-001',
//         rent_day: 35.0,
//         rent_week: 200.0,
//         rent_month: 700.0,
//         is_available: 1,
//         condition: 'excellent',
//         Instrument_id_Instrument: 5,
//       },
//       {
//         id_Item: 19,
//         barcode: 'hap-002',
//         rent_day: 35.0,
//         rent_week: 200.0,
//         rent_month: 700.0,
//         is_available: 1,
//         condition: 'excellent',
//         Instrument_id_Instrument: 5,
//       },
//       {
//         id_Item: 20,
//         barcode: 'hap-003',
//         rent_day: 35.0,
//         rent_week: 200.0,
//         rent_month: 700.0,
//         is_available: 1,
//         condition: 'good',
//         Instrument_id_Instrument: 5,
//       },
//       {
//         id_Item: 21,
//         barcode: 'hap-004',
//         rent_day: 35.0,
//         rent_week: 200.0,
//         rent_month: 700.0,
//         is_available: 1,
//         condition: 'good',
//         Instrument_id_Instrument: 5,
//       },
//       {
//         id_Item: 22,
//         barcode: 'drm-001',
//         rent_day: 25.0,
//         rent_week: 140.0,
//         rent_month: 500.0,
//         is_available: 1,
//         condition: 'excellent',
//         Instrument_id_Instrument: 6,
//       },
//       {
//         id_Item: 23,
//         barcode: 'drm-002',
//         rent_day: 25.0,
//         rent_week: 140.0,
//         rent_month: 500.0,
//         is_available: 1,
//         condition: 'excellent',
//         Instrument_id_Instrument: 6,
//       },
//       {
//         id_Item: 24,
//         barcode: 'drm-003',
//         rent_day: 25.0,
//         rent_week: 140.0,
//         rent_month: 500.0,
//         is_available: 1,
//         condition: 'good',
//         Instrument_id_Instrument: 6,
//       },
//       {
//         id_Item: 25,
//         barcode: 'drm-004',
//         rent_day: 25.0,
//         rent_week: 140.0,
//         rent_month: 500.0,
//         is_available: 1,
//         condition: 'good',
//         Instrument_id_Instrument: 6,
//       },
//       {
//         id_Item: 26,
//         barcode: 'drm-005',
//         rent_day: 25.0,
//         rent_week: 140.0,
//         rent_month: 500.0,
//         is_available: 1,
//         condition: 'good',
//         Instrument_id_Instrument: 6,
//       },
//       {
//         id_Item: 27,
//         barcode: 'acc-001',
//         rent_day: 20.0,
//         rent_week: 110.0,
//         rent_month: 400.0,
//         is_available: 1,
//         condition: 'excellent',
//         Instrument_id_Instrument: 7,
//       },
//       {
//         id_Item: 28,
//         barcode: 'acc-002',
//         rent_day: 20.0,
//         rent_week: 110.0,
//         rent_month: 400.0,
//         is_available: 1,
//         condition: 'excellent',
//         Instrument_id_Instrument: 7,
//       },
//       {
//         id_Item: 29,
//         barcode: 'acc-003',
//         rent_day: 20.0,
//         rent_week: 110.0,
//         rent_month: 400.0,
//         is_available: 1,
//         condition: 'good',
//         Instrument_id_Instrument: 7,
//       },
//       {
//         id_Item: 30,
//         barcode: 'acc-004',
//         rent_day: 20.0,
//         rent_week: 110.0,
//         rent_month: 400.0,
//         is_available: 1,
//         condition: 'good',
//         Instrument_id_Instrument: 7,
//       },
//       {
//         id_Item: 31,
//         barcode: 'acc-005',
//         rent_day: 20.0,
//         rent_week: 110.0,
//         rent_month: 400.0,
//         is_available: 1,
//         condition: 'good',
//         Instrument_id_Instrument: 7,
//       },
//       {
//         id_Item: 32,
//         barcode: 'acc-006',
//         rent_day: 20.0,
//         rent_week: 110.0,
//         rent_month: 400.0,
//         is_available: 1,
//         condition: 'good',
//         Instrument_id_Instrument: 7,
//       },
//       {
//         id_Item: 33,
//         barcode: 'acc-007',
//         rent_day: 20.0,
//         rent_week: 110.0,
//         rent_month: 400.0,
//         is_available: 1,
//         condition: 'good',
//         Instrument_id_Instrument: 7,
//       },
//     ];
//     return { productCategories, items, instruments };
//   }
// }
