AWSTemplateFormatVersion: '2010-09-09'
Description: 'SoitinStock - Cognito Authentication'

Resources:
    UserPool:
        Type: AWS::Cognito::UserPool
        Properties:
            UserPoolName: SoitinStock-UserPool

            UsernameAttributes:
                - email

            AutoVerifiedAttributes:
                - email

            Policies:
                PasswordPolicy:
                    MinimumLength: 8
                    RequireUppercase: true
                    RequireLowercase: true
                    RequireNumbers: true
                    RequireSymbols: false

            Schema:
                - Name: email
                  Required: true
                  Mutable: true

    UserPoolClient:
        Type: AWS::Cognito::UserPoolClient
        Properties:
            ClientName: SoitinStock-Client
            UserPoolId: !Ref UserPool

            GenerateSecret: false # IMPORTANT for frontend apps

            ExplicitAuthFlows:
                - ALLOW_USER_PASSWORD_AUTH
                - ALLOW_ADMIN_USER_PASSWORD_AUTH
                - ALLOW_REFRESH_TOKEN_AUTH

            AllowedOAuthFlowsUserPoolClient: true

            AllowedOAuthFlows:
                - code

            AllowedOAuthScopes:
                - email
                - openid
                - profile

            SupportedIdentityProviders:
                - COGNITO

            # HARDCODED! EDIT if change. Current callback/logout url, update to proper urls later
            CallbackURLs:
                - https://d2jvgghzsyqabk.cloudfront.net/

            LogoutURLs:
                - https://d2jvgghzsyqabk.cloudfront.net/

    UserPoolDomain:
        Type: AWS::Cognito::UserPoolDomain
        Properties:
            Domain: soitinstock-auth-2026
            UserPoolId: !Ref UserPool

Outputs:
    UserPoolId:
        Value: !Ref UserPool
        Export:
            Name: SoitinStock-UserPoolId

    UserPoolClientId:
        Value: !Ref UserPoolClient
        Export:
            Name: SoitinStock-UserPoolClientId

    CognitoLoginURL:
        Value: !Sub
            - 'https://${Domain}/login?client_id=${ClientId}&response_type=code&scope=openid+email&redirect_uri=${Redirect}'
            - Domain: soitinstock-auth-2026.auth.eu-north-1.amazoncognito.com
              # ClientId: 1b08n5k49r4pnqegckcoodloje
              ClientId: !Ref UserPoolClient
              Redirect: https://d2jvgghzsyqabk.cloudfront.net/
